// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션은 반드시 Direct URL(5432)로 연결해야 합니다
    url: process.env["DIRECT_URL"],
  },
});
